config/routes.rb
Rails.application.routes.draw do

  # TODO: `root to:` の設定も後ほどお願いします！
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  get 'map', to: 'map#index'
  
  get 'clean_companies/search', to: 'search#index'
  get 'clean_companies/results', to: 'results#show'
  
  resources :users
  resources :clean_companies do
    resources :clean_reviews
    resources :clean_prefectures
    resources :clean_charges
  end
  
  resources :clean_companies do
    resources :clean_threads
    get 'clean_threads/post', to: 'clean_threads#postshow'
    post 'clean_threads/post'
  end
  
  get '/auth/:provider/callback',    to: 'users#create',       as: :auth_callback
  get '/auth/failure',               to: 'users#auth_failure', as: :auth_failure
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/clean_company.rb
class CleanCompany < ApplicationRecord
  before_save { self.email.downcase! }

  mount_uploader :image_url, ImageUploader

  belongs_to :user

  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :tel, presence: true, length: { maximum: 11 },
                format: { with: /\A\d{10}$|^\d{11}\z/}
  validates :image_url, presence: true, on: [:create]

  has_many :clean_prefectures,dependent: :delete_all
  has_many :prefectures, through: :clean_prefectures
  has_many :workings, through: :clean_prefectures, source: :prefecture
  
  has_many :charges,dependent: :delete_all
  
  has_many :clean_reviews,dependent: :delete_all
  has_many :users,through: :clean_reviews, source: :user

  has_many :clean_threads,dependent: :destroy
  has_many :message_users,through: :clean_threads, source: :clean_company

  def working?(prefecture)
    self.workings.include?(prefecture)
  end

  def contact(account_type,user_id)
    if account_type == 2 && user_id != params[:id]
      return false
    else
      return true
    end  
  end

  def self.search(search)
    if search
      self.where(['prefecture_id LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
    else
      self.all #全て表示。User.は省略
    end
  end

end

app/controllers/clean_companies_controller.rb
class CleanCompaniesController < ApplicationController
  
  def index
    @companies = CleanCompany.all
  end
  
  def show
    @company = CleanCompany.find(params[:id])
    @threads = @company.clean_threads
    @thread = CleanThread.find_by(clean_company_id: params[:id]) && CleanThread.find_by(user_id: current_user.id)
  end
  
  def new
    @company = CleanCompany.new
  end
  
  def create
    
    @company = CleanCompany.new(user_id: params[:user_id],
                                name: params[:clean_company][:name],
                                image_url: params[:clean_company][:image_url],
                                tel: params[:clean_company][:tel],
                                email: params[:clean_company][:email])
    
    #binding.pry
    
    if @company.save
      flash[:success] = '会社を登録いたしました。'
      redirect_to new_clean_company_clean_prefecture_path(@company)
    else
      flash.now[:danger] = '会社の登録に失敗しました。'
      render :new and return
    end

  end
  
  def destroy
    CleanCompany.find(params[:id]).destroy
    flash[:success] = "Company deleted"
    redirect_to user_path(current_user.id)
  end
  
  def edit
    @company = CleanCompany.find(params[:id])
  end
  
  def update
    @company = CleanCompany.find(params[:id])
    #binding.pry
    if @company.update(name: params[:clean_company][:name],
                      image_url: params[:clean_company][:image_url],
                      tel: params[:clean_company][:tel],
                      email: params[:clean_company][:email])
       #binding.pry
       redirect_to clean_company_path(@company)
    else
      render :edit
    end
  end

  private
  
  # Strong Parameter

  def clean_company_params
    params.require(:clean_company).permit(:name, :tel, :email)
  end

end

app/helpers/clean_companies_helper.rb
module CleanCompaniesHelper
  def gravatar_url(clean_company, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(clean_company.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
  
  def get_back
    if current_user.is_hotel
      link_to '<一覧に戻る', clean_companies_path, class: 'btn btn-default'
    elsif current_user.is_clean_company
      link_to '<一覧に戻る', user_path(current_user.id), class: 'btn btn-default'
    end
  end

  # おすすめ
  # is_xxx?
  def is_thread?
    if CleanThread.find_by(clean_company_id: params[:id]) && CleanThread.find_by(user_id: current_user.id)
      true
    else
      false
    end
  end
end

app/views/clean_companies/_companies.html.erb
<% if companies.present? %>
  <div class="row">
    <% companies.each do |company| %>
      <div class="company">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <%= image_tag(company.image_url, :size => "250x100", :class => "img-circle") %>
            </div>
            <div class="panel-body">
              <% if company.persisted? %>
                <p class="company-title"><%= link_to company.name, company %></p>
              <% else %>
                <p class="company-title"><%= company.name %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/clean_companies/edit.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6 col-xs-offset-0">
    <div class="panel panel-default">
      <div class="panel-heading">会社情報を編集（１／３）</div>
      <div class="panel-body">
        <%= form_for(@company) do |f|%>
          <%= render 'layouts/error_messages', model: f.object %>

          <%= hidden_field_tag :user_id, current_user.id %>
          
          <div class = "form-group">
            <%= f.label :name, "会社名"%>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class = "form-group">
            <%= f.label :image_url,"ユーザー画像" %>
            <%= f.file_field :image_url %>
          </div>
          
          <div class = "form-group">
            <%= f.label :email, "メールアドレス"%>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          
          <div class = "form-group">
            <%= f.label :tel, "電話番号"%>
            <%= f.text_field :tel, class: 'form-control' %>
          </div>
          
          <div class = "text-right">
            <%= f.submit '作業地域編集画面へ',class: 'btn btn-success' %><br />
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/clean_companies/index.html.erb
<%= get_back_top %>
<%= render 'clean_companies/companies', companies: @companies %>

app/views/clean_companies/new.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6 col-xs-offset-0">
    <div class="panel panel-default">
      <div class="panel-heading">会社登録（１／３）</div>
      <div class="panel-body">
        <%= form_for(@company) do |f|%>
          <%= render 'layouts/error_messages', model: f.object %>

          <%= hidden_field_tag :user_id, current_user.id %>
          <div class = "form-group">
            <%= f.label :name, "会社名"%>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class = "form-group">
            <%= f.label :image_url,"ユーザー画像" %>
            <%= f.file_field :image_url %>
          </div>
          
          <div class = "form-group">
            <%= f.label :email, "メールアドレス"%>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          
          <div class = "form-group">
            <%= f.label :tel, "電話番号"%>
            <%= f.text_field :tel, class: 'form-control' %>
          </div>
          
          <div class = "text-right">
            <%= f.submit '作業地域選択画面へ',class: 'btn btn-success' %><br />
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/clean_companies/show.html.erb
<%= get_back %>
<div class="clean_company-profile">
  <div class="icon text-center">
    <%= image_tag(@company.image_url, :size => "300x300", :class => "img-circle") %>
  </div>
  <div class="name text-center">
    <h1><%= @company.name %></h1>
    <%if current_user.is_clean_company%>
      <%= link_to "削除",clean_company_path(@company), method: :delete, data: { confirm: "こちらの会社を削除します。本当によろしいですか?" },class: 'btn btn-danger btn-sm' %>
    <%end%>
    <!--
    <% if current_user.is_clean_company %>
      <div class="text-center">
      <%= link_to '会社情報を変更する', edit_clean_company_path(@company),class: 'btn btn-link' %>
      </div>
    <% end %>
    -->
  </div>
</div>
<div class="row">
  
  <div class="col-md-3 col-sm-6 col-xs-12 col-md-offset-3">
    <div class="clean_company">
      <div class="col-xs-6 col-md-10 col-lg-10">
        <ul class="nav nav-tabs nav-justified">
          <li class="<%= 'active' if current_page?(clean_company_path(@company)) %>"><%= link_to clean_company_path(@company) do %>サービス内容 <% end %></li>
          <li class="<%= 'active' if current_page?(clean_company_clean_reviews_path(@company)) %>"><%= link_to clean_company_clean_reviews_path(@company) do %>レビュー <% end %></li>
        </ul>
      </div>
      <div class = "clean_info">    
        <dl>
          <dt>ユーザー名</dt>
          <dd><%= @company.user.name %></dd>
          <dt>☎️</dt>
          <dd><%= @company.tel %></dd>
          <dt>作業可能地域
          
          <!--
          <%if current_user.is_clean_company%>
            <%= link_to '編集', edit_clean_company_clean_prefecture_path(@company),class: 'btn btn-link' %>
          <%end%>
          -->
          </dt>
          <dd></dd>
          <dt></dt>
          <dd></dd>
          <dd>
            <% @company.workings.each do |company| %>
              <%= company.prefecture %>  
            <% end %>
          </dd>
          <dt>部屋の広さ(平米)</dt>
          <dd>清掃料金</dd>
          <% @company.charges.each do |company| %>
            <dt><%= company.square_meters_min %>〜<%= company.square_meters_max %></dt> 
            <dd>¥<%= company.charge %></dd>
          <% end %>
          <!--
          <%if current_user.is_clean_company%>
            <dt>
            <%= link_to '編集', edit_clean_company_clean_charge_path(@company),class: 'btn btn-link' %>
            </dt>
          <%end%>
          -->
          <dt></dt>
          <dd></dd>
        </dl>

        <!-- if スレッドが存在する → スレッド画面 show -->
        <!-- if スレッドが存在しない → スレッド新規画面 new -->
        <% if current_user.is_hotel %>
          <!-- ログインユーザーが民泊管理者の場合 -->
          <% if current_user.has_thread?(@company) %>
            <dl><dt><%= link_to 'メッセージ画面へ', clean_company_clean_thread_path(@company, current_user.get_thread_id(@company)), class: 'btn btn-primary'%></dt></dl>
          <% else %>
            <dl><dt><%= link_to 'メッセージ画面へ', new_clean_company_clean_thread_path(@company), class: 'btn btn-primary'%></dt></dl>
          <% end %>
        
        <% elsif current_user.is_clean_company %>
          <!-- ログインユーザーが清掃業者の場合 -->
          <dd>
            <ul class="media-list">
              <% @threads.each do |thread| %>
                <li class="media">
                  <div class="pull-left">
                    <img src="<%= gravatar_url(thread.user, options = { size: 20 }) %>" alt="" class="img-circle">
                  </div>
                  <div class="pull-left">
                    <%= link_to thread.user.name + 'へのメッセージ画面へ', clean_company_clean_thread_path(params[:id],thread.id) %>
                  </div>
                </li>
              <% end %>
            </ul>
          </dd>
        <% end %>
      </div>
    </div>
  </div>
</div>