config/routes.rb
Rails.application.routes.draw do

  # TODO: `root to:` の設定も後ほどお願いします！
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  get 'map', to: 'map#index'
  
  get 'clean_companies/search', to: 'search#index'
  get 'clean_companies/results', to: 'results#show'
  
  resources :users
  resources :clean_companies do
    resources :clean_reviews
    resources :clean_prefectures
    resources :clean_charges
  end
  
  resources :clean_companies do
    resources :clean_threads
    get 'clean_threads/post', to: 'clean_threads#postshow'
    post 'clean_threads/post'
  end
  
  get '/auth/:provider/callback',    to: 'users#create',       as: :auth_callback
  get '/auth/failure',               to: 'users#auth_failure', as: :auth_failure
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/views/toppages/index.html.erb
<% content_for :cover do %>
  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        <h1>民泊物件と清掃業者マッチングサービス</h1>
          <% if logged_in? %>
            <% if current_user.is_hotel%>
              <%= link_to '清掃業者検索をする', clean_companies_search_url, class: 'btn btn-primary btn-lg' %>
            <% elsif%>
              <%= link_to '会社情報を入力する', new_clean_company_url, class: 'btn btn-primary btn-lg' %>
            <% end %>
            
          <% else %>
            <%= link_to 'Cleansを始める', signup_path, class: 'btn btn-success btn-lg' %>
          <% end %>
      </div>
    </div>
  </div>
<% end %>