config/routes.rb
Rails.application.routes.draw do

  # TODO: `root to:` の設定も後ほどお願いします！
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  get 'map', to: 'map#index'
  
  get 'clean_companies/search', to: 'search#index'
  get 'clean_companies/results', to: 'results#show'
  
  resources :users
  resources :clean_companies do
    resources :clean_reviews
    resources :clean_prefectures
    resources :clean_charges
  end
  
  resources :clean_companies do
    resources :clean_threads
    get 'clean_threads/post', to: 'clean_threads#postshow'
    post 'clean_threads/post'
  end
  
  get '/auth/:provider/callback',    to: 'users#create',       as: :auth_callback
  get '/auth/failure',               to: 'users#auth_failure', as: :auth_failure
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/clean_prefecture.rb
class CleanPrefecture < ApplicationRecord
  belongs_to :clean_company
  belongs_to :prefecture

  validates :clean_company_id, presence:true
  validates :prefecture_id, presence:true
end

app/controllers/clean_prefectures_controller.rb
class CleanPrefecturesController < ApplicationController
  def new
    @prefecture = CleanPrefecture.new
  end
  
  def create

    if params[:prefecture_id].nil?
      # 完璧に正しくありませんが、このようにすると動きます
      @prefecture = CleanPrefecture.new
      flash.now[:danger] = '作業可能地域が入力されていません。'
      render :new and return
    end


    @prefecture = CleanPrefecture.new
    
    
    params[:prefecture_id].each do |p|

      # ブラウザバックの考慮として、既に都道府県が登録されている場合は、ループをスキップする
      if CleanPrefecture.exists?(clean_company_id: params[:clean_company_id], prefecture_id: p.to_i)
        next
      end

      @prefecture = CleanPrefecture.new(
        clean_company_id: params[:clean_company_id],
        prefecture_id: p.to_i
      )
      #binding.pry
      if @prefecture.save
        flash.now[:success] = '作業地域の登録しました。'
        next
      else
        flash.now[:danger] = '作業地域の登録に失敗しました。'
        render :new and return
      end
      
    end
    
    redirect_to new_clean_company_clean_charge_path(params[:clean_company_id]) and return
  end
  
  def edit
    @prefecture = CleanPrefecture.find(params[:clean_company_id])
  end
  
  def update
    if params[:prefecture_id].nil?
      # 完璧に正しくありませんが、このようにすると動きます
      @prefecture = CleanPrefecture.find(params[:clean_company_id])
      flash.now[:danger] = '作業可能地域が入力されていません。'
      render :edit and return
    end
    
    params[:prefecture_id].each do |p|

      # ブラウザバックの考慮として、既に都道府県が登録されている場合は、ループをスキップする
      if CleanPrefecture.exists?(clean_company_id: params[:clean_company_id], prefecture_id: p.to_i)
        next
      end

      #binding.pry
      if @prefecture = CleanPrefecture.update(clean_company_id: params[:clean_company_id],prefecture_id: p.to_i)
        flash.now[:success] = '作業地域の登録しました。'
        redirect_to clean_company_path(params[:clean_company_id]) and return
      else
        flash.now[:danger] = '作業地域の登録に失敗しました。'
        render :edit and return
      end
      
    end
    
  end
  
end

app/views/clean_prefectures/edit.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6 col-xs-offset-0">
    <div class="panel panel-default">
      <div class="panel-heading">会社登録（２／３）</div>
      <div class="panel-body">
        <%= form_tag(clean_company_clean_prefecture_path, method: 'put') do %>
          <%= render 'layouts/error_messages', model: @prefecture %>
          <div class = "form-group area">
            <%= label_tag 'area', "作業可能地域"%>
          </div>
          
          <div class = "form-group">
            <%= label_tag 'area', "関東地区"%>
          </div>
          
          <div class = "form-group">
            <%= check_box_tag 'prefecture_id[]',checked_value = "13" %>
            <%= label_tag :prefecture, "東京都 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "14" %>
            <%= label_tag :prefecture, "神奈川県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "11" %>
            <%= label_tag :prefecture, "埼玉県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "12" %>
            <%= label_tag :prefecture, "千葉県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "8" %>
            <%= label_tag :prefecture, "茨城県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "9" %>
            <%= label_tag :prefecture, "栃木県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "10" %>
            <%= label_tag :prefecture, "群馬県 " %>
          </div>
          
          <div class = "form-group">
            <%= label_tag 'area', "関西地区"%>
          </div>
          
          <div class = "form-group">
            <%= check_box_tag 'prefecture_id[]',checked_value = "27" %>
            <%= label_tag :prefecture, "大阪府 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "26" %>
            <%= label_tag :prefecture, "京都府 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "29" %>
            <%= label_tag :prefecture, "奈良県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "28" %>
            <%= label_tag :prefecture, "兵庫県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "25" %>
            <%= label_tag :prefecture, "滋賀県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "30" %>
            <%= label_tag :prefecture, "和歌山県 " %>
          </div>
          
          
            
          
          <div class = "text-right">
            <%= submit_tag '作業地域更新へ',class: 'btn btn-success' %><br />
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/clean_prefectures/new.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6 col-xs-offset-0">
    <div class="panel panel-default">
      <div class="panel-heading">会社登録（２／３）</div>
      <div class="panel-body">
        <%= form_tag(clean_company_clean_prefectures_path, method: 'post') do %>
          <%= render 'layouts/error_messages', model: @prefecture %>
          <div class = "form-group area">
            <%= label_tag 'area', "作業可能地域"%>
          </div>
          
          <div class = "form-group">
            <%= label_tag 'area', "関東地区"%>
          </div>
          
          <div class = "form-group">
            <%= check_box_tag 'prefecture_id[]',checked_value = "13" %>
            <%= label_tag :prefecture, "東京都 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "14" %>
            <%= label_tag :prefecture, "神奈川県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "11" %>
            <%= label_tag :prefecture, "埼玉県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "12" %>
            <%= label_tag :prefecture, "千葉県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "8" %>
            <%= label_tag :prefecture, "茨城県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "9" %>
            <%= label_tag :prefecture, "栃木県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "10" %>
            <%= label_tag :prefecture, "群馬県 " %>
          </div>
          
          <div class = "form-group">
            <%= label_tag 'area', "関西地区"%>
          </div>
          
          <div class = "form-group">
            <%= check_box_tag 'prefecture_id[]',checked_value = "27" %>
            <%= label_tag :prefecture, "大阪府 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "26" %>
            <%= label_tag :prefecture, "京都府 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "29" %>
            <%= label_tag :prefecture, "奈良県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "28" %>
            <%= label_tag :prefecture, "兵庫県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "25" %>
            <%= label_tag :prefecture, "滋賀県 " %>
            <%= check_box_tag 'prefecture_id[]',checked_value = "30" %>
            <%= label_tag :prefecture, "和歌山県 " %>
          </div>
          
          
            
          
          <div class = "text-right">
            <%= submit_tag '料金入力画面へ',class: 'btn btn-success' %><br />
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>